

package love.forte.plugin.suspendtrans.oracle;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link love.forte.plugin.suspendtrans.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/oracle")
@TestDataPath("$PROJECT_ROOT")
public class OracleTestRunnerGenerated extends AbstractOracleTestRunner {
  private void run(String fileName) {
    runTest("src/testData/oracle/" + fileName);
  }

  @Test
  public void testAllFilesPresentInOracle() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/oracle"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("asProperty.kt")
  public void testAsProperty() {
    run("asProperty.kt");
  }

  @Test
  @TestMetadata("coroutineScope.kt")
  public void testCoroutineScope() {
    run("coroutineScope.kt");
  }

  @Test
  @TestMetadata("generatedNameConflict.kt")
  public void testGeneratedNameConflict() {
    run("generatedNameConflict.kt");
  }

  @Test
  @TestMetadata("generatedPropertyClash.kt")
  public void testGeneratedPropertyClash() {
    run("generatedPropertyClash.kt");
  }

  @Test
  @TestMetadata("genericNullableReceiver.kt")
  public void testGenericNullableReceiver() {
    run("genericNullableReceiver.kt");
  }

  @Test
  @TestMetadata("interfaceDefault.kt")
  public void testInterfaceDefault() {
    run("interfaceDefault.kt");
  }

  @Test
  @TestMetadata("twoLevelOverride.kt")
  public void testTwoLevelOverride() {
    run("twoLevelOverride.kt");
  }

  @Test
  @TestMetadata("valueClass.kt")
  public void testValueClass() {
    run("valueClass.kt");
  }
}
