

package love.forte.plugin.suspendtrans.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link love.forte.plugin.suspendtrans.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/codegen")
@TestDataPath("$PROJECT_ROOT")
public class CodeGenTestRunnerGenerated extends AbstractCodeGenTestRunner {
  private void run(String fileName) {
    runTest("src/testData/codegen/" + fileName);
  }

  @Test
  @TestMetadata("alias.kt")
  public void testAlias() {
    run("alias.kt");
  }

  @Test
  public void testAllFilesPresentInCodegen() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/codegen"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("asProperty.kt")
  public void testAsProperty() {
    run("asProperty.kt");
  }

  @Test
  @TestMetadata("basic.kt")
  public void testBasic() {
    run("basic.kt");
  }

  @Test
  @TestMetadata("implOverriden.kt")
  public void testImplOverriden() {
    run("implOverriden.kt");
  }

  @Test
  @TestMetadata("implOverridenGeneric.kt")
  public void testImplOverridenGeneric() {
    run("implOverridenGeneric.kt");
  }

  @Test
  @TestMetadata("jvmReactive.kt")
  public void testJvmReactive() {
    run("jvmReactive.kt");
  }

  @Test
  @TestMetadata("markName.kt")
  public void testMarkName() {
    run("markName.kt");
  }

  @Test
  @TestMetadata("nullmarkMode.kt")
  public void testNullmarkMode() {
    run("nullmarkMode.kt");
  }

  @Test
  @TestMetadata("nullmarkModeWhere.kt")
  public void testNullmarkModeWhere() {
    run("nullmarkModeWhere.kt");
  }

  @Test
  @TestMetadata("opt.kt")
  public void testOpt() {
    run("opt.kt");
  }

  @Test
  @TestMetadata("override.kt")
  public void testOverride() {
    run("override.kt");
  }

  @Test
  @TestMetadata("typeAttr.kt")
  public void testTypeAttr() {
    run("typeAttr.kt");
  }

  @Test
  @TestMetadata("typeAttrNested.kt")
  public void testTypeAttrNested() {
    run("typeAttrNested.kt");
  }

  @Test
  @TestMetadata("varargParam.kt")
  public void testVarargParam() {
    run("varargParam.kt");
  }
}
