

package love.forte.plugin.suspendtrans.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link love.forte.plugin.suspendtrans.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticOracleTestRunnerGenerated extends AbstractDiagnosticOracleTestRunner {
  private void run(String fileName) {
    runTest("src/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("bridgeCallSite.kt")
  public void testBridgeCallSite() {
    run("bridgeCallSite.kt");
  }

  @Test
  @TestMetadata("bridgeRedeclaration.kt")
  public void testBridgeRedeclaration() {
    run("bridgeRedeclaration.kt");
  }

  @Test
  @TestMetadata("unresolvedBridge.kt")
  public void testUnresolvedBridge() {
    run("unresolvedBridge.kt");
  }
}
