

package love.forte.plugin.suspendtrans.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link love.forte.plugin.suspendtrans.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/runtime")
@TestDataPath("$PROJECT_ROOT")
public class RuntimeOracleTestRunnerGenerated extends AbstractRuntimeOracleTestRunner {
  private void run(String fileName) {
    runTest("src/testData/runtime/" + fileName);
  }

  @Test
  public void testAllFilesPresentInRuntime() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/runtime"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("asProperty.kt")
  public void testAsProperty() {
    run("asProperty.kt");
  }

  @Test
  @TestMetadata("axisOverrideLv20Jvm8.kt")
  public void testAxisOverrideLv20Jvm8() {
    run("axisOverrideLv20Jvm8.kt");
  }

  @Test
  @TestMetadata("axisScopeLv24Jvm21.kt")
  public void testAxisScopeLv24Jvm21() {
    run("axisScopeLv24Jvm21.kt");
  }

  @Test
  @TestMetadata("axisValueClassLv22Jvm17.kt")
  public void testAxisValueClassLv22Jvm17() {
    run("axisValueClassLv22Jvm17.kt");
  }

  @Test
  @TestMetadata("consecutiveModules.kt")
  public void testConsecutiveModules() {
    run("consecutiveModules.kt");
  }

  @Test
  @TestMetadata("coroutineScope.kt")
  public void testCoroutineScope() {
    run("coroutineScope.kt");
  }

  @Test
  @TestMetadata("genericNullableReceiver.kt")
  public void testGenericNullableReceiver() {
    run("genericNullableReceiver.kt");
  }

  @Test
  @TestMetadata("interfaceDefault.kt")
  public void testInterfaceDefault() {
    run("interfaceDefault.kt");
  }

  @Test
  @TestMetadata("twoLevelOverride.kt")
  public void testTwoLevelOverride() {
    run("twoLevelOverride.kt");
  }

  @Test
  @TestMetadata("valueClass.kt")
  public void testValueClass() {
    run("valueClass.kt");
  }

  @Test
  @TestMetadata("wrongDispatchReceiver.kt")
  public void testWrongDispatchReceiver() {
    run("wrongDispatchReceiver.kt");
  }
}
